---
- name: Update APT
  hosts: alicloud
  tasks:
  - name: Update apt repo and cache
    apt:  update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install nodejs and npm
    apt:
      pkg:
        - nodejs
        - npm

- name: Create Linux User for node app
  hosts: alicloud
  tasks:
    - name: create a Linux user group
      group: 
        name: "{{user_name}}"
        state: present
    - name: create a linux user
      user:
        name: "{{user_name}}"
        group: "{{user_name}}"


- name:  deploy nodejs app
  hosts: alicloud
  become: True
  become_user: "{{user_name}}"
  tasks: 
    - name: Unpack the node js file
      unarchive: 
        src: /Users/flybird/Desktop/ANSIBLE/Ansible-Learning/developing-with-docker-1.0.0.tgz
        dest: /home/"{{user_name}}"
    - name: install node.js package
      npm:
        path: /home/"{{user_name}}"/package
    - name: Start the application
      command: 
        chdir: /home/"{{user_name}}"/package
        cmd: node server
      async: 1000
      poll: 0
    - name: Eusure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}

### deploy node by root user