---
- name: Install java and net-tools
  hosts: nexus_server
  tasks:
  - name: Update apt repo and cache
    apt:  update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install Java 8
    apt: name=openjdk-8-jre-headless
  - name: Install net-tools
    apt: name=net-tools

- name: Download Nexus Package
  hosts: nexus_server
  tasks:
  - name: stat the file
    stat:
      path: /opt/nexus
    register: file_stat
  - debug: msg={{file_stat}}  

  - name: Download Nexus
    get_url: 
      url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
      dest: /opt/
    register: nexus_package
  - debug: msg={{nexus_package}}
    when: not file_stat.stat.exists

  - name: Untar nexus installer
    unarchive: 
      src: "{{nexus_package.dest}}"
      dest: /opt/
      remote_src: yes
    when: not file_stat.stat.exists

  - name: find nexus folder
    find:
      path: /opt
      pattern: "nexus-*"
      file_type: directory
    register: find_result
  - debug: msg={{find_result}}

  - name: rename nexus folder
    command: mv {{find_result.files[0].path}} /opt/nexus
    when: not file_stat.stat.exists

- name: Create Linux User for node app
  hosts: nexus_server
  vars_files:
    - project-vars
  tasks:
    - name: create a Linux user group
      group: 
        name: "{{group_name}}"
        state: present
    - name: create a linux user
      user:
        name: "{{user_name}}"
        group: "{{group_name}}"
    - name: Make user owner of nexus folder
      ansible.builtin.file:
        path: /opt/nexus
        owner: "{{user_name}}"
        group: "{{group_name}}"
        recurse: yes
    - name: Make user owner of nexus folder
      ansible.builtin.file:
        path: /opt/sonatype-work
        owner: "{{user_name}}"
        group: "{{group_name}}"
        recurse: yes   

- name: Start nexus with nexus user
  hosts: nexus_server
  vars_files:
    - project-vars
  tasks:
    - name: Set run_as_user nexus
      blockinfile:
        path: /opt/nexus/bin/nexus.rc
        block: |
          run_as_user="{{user_name}}"
    
    - name: Start Nexus
      become: True
      become_user: "{{user_name}}"
      command: /opt/nexus/bin/nexus start
    

- name: Verify nexus is running
  hosts: nexus_server
  vars_files:
  - project-vars
  tasks:
    - name: Verify Nexus Process
      command: ps aux | grep nexus
      register: check_nexus_process
    - debug: msg={{check_nexus_process}}

    - name: Wait one minute
      pause:
        minutes: 1

    - name: Verify Nexus Internet stats
      command: netstat -lnpt
      register: check_nexus
    - debug: msg={{check_nexus.stdout_lines}}


    # - name: replace line in file
    #   lineinfile:
    #     path: /opt/nexus/bin/nexus.rc
    #     regexp: '^# BEGIN ANSIBLE MANAGED BLOCK'
    #     line:  ''



